[package]
name = "compiler"
version = "0.1.0"
edition = "2021"

[dependencies]
itertools = "0.13.0"
regex = "1.10.6"
tracing = { version = "0.1.40", default-features = false }
tracing-subscriber = { version = "0.3.18" }
